AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'code-commit'

Parameters:
  MaeEks:
    Type: string

Resources:
  MaeEksCodeCommit:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MaeEksRepo
      RepositoryDescription: Cluster
      